# Generated by Django 4.1 on 2023-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
